import MainLayout from "@/components/MainLayout";
// import "@progress/kendo-theme-fluent";
// import "@progress/kendo-theme-default/dist/all.css";
import "@progress/kendo-theme-bootstrap/dist/all.scss";
import "bootstrap/scss/bootstrap.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kendo Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout>{children}</MainLayout>
      </body>
      <style>{`body { font-family: "Segoe UI", sans-serif; } :root { --kendo-font-size: 18px; } `}</style>
    </html>
  );
}
